### ISSUE TITLE
Try rewriting sdk generator by ourselves

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/tinka-generator-openapi#11] opened 2017-05-21 13:09 UTC
A __bold__ idea, but let's consider this
- There's one little problem with the generated ts file from swagger codegen. Property names get converted from underscore to camelCase. When does this happen? It happens somewhere in Java code after running docker command line. To investigate(install java editor, set up environment, and enable debugging), fix, and deploy (create a pull request to swagger, or create our own docker image) would take similar amount of time to write a working (but not completed regarding every aspects of spec) sdk generator by our own. 
- Mustache syntax is awful.
- There's little flexibility when using Mustache template that receives data from some java code. For example, we get the path string like this `/products/{id}`, but we want to change `{id}` to be the real id that is passed to the method via `params` like this `/products/params.id`. But this is not possible because Mustache has no `replace` method. Instead we need to do the `replace` in the generated code itself like this `"/products/{id}".replace("{id}", params.id)` which is ugly, or create a method `bakeUrl(...)` to handle the replace which is less uglier.
- Running docker command line will create files for us locally. But this project won't be used locally, this project will be a dev dependency for other projects. Other projects will use it by running our cli. I think it's a challenge to create a cli (using Node or Ruby?) that can run docker command line, which can take a spec.json file from a calling party, and mount a directory of the calling party as a data volume.
- If we create sdk generator by our own, we can have classes that can be reused to create an sdk for mobile platforms. I imagine that initially we don't need to follow every specifications detailed in the [OpenAPI-Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md), we just need to create something that just works, then incrementally add more works to comply with the OpenAPI.

**Comment by paibamboo** [comment] 2017-07-05 15:02
@cyberhck Has the issue in tinka been addressed?

**Comment by cyberhck** [comment] 2017-07-07 00:12
Which issue in tinka again? Do you mean the publishing? I think so.

**Comment by wmathes** [comment] 2017-07-10 01:00
>There's one little problem with the generated ts file from swagger codegen. Property names get converted from underscore to camelCase.

This correct and expected behaviour. Don't change this. Instead look for the real source of the problem? shop-api's responses should have only camelCased properties. If it doesn't, then open an issue there :)

**Comment by paibamboo** [comment] 2017-07-14 03:43
And should the properties in spec.json be camelCased or underscore_cased? If underscore_cased, we need to edit code in this repo too to convert underscored_cased from spec.json to camelCased in sdk.ts.

**Comment by cyberhck** [comment] 2017-07-14 03:48
actually `spec.json` should already use camelCased because that already accepts `application/json` which has standard to use camelCase. And API itself should accept and return in camelCase.

In that case we'll get spec file in camelCase, then we don't need to change a thing in tinka-generator-openapi.

If that's not the case, we'll need to create some kind of map which will convert it to camelCase and later turn it back to snake_case (which I don't think make sense)

**Comment by wmathes** [comment] 2017-07-17 04:32
this should be handled this in shop-api

**Comment by cyberhck** [comment] 2017-10-25 08:28
Since we did rewrite sdk generator ourselves, I'm closing this issue now, if there's some discussion to be had on this, feel free to open a new issue.

**Closed by cyberhck** 2017-10-25 08:28 UTC
Labels: enhancement
